# Generated by Django 3.2.13 on 2022-04-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNo', models.TextField()),
                ('duration', models.IntegerField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_a', to='new.airport')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_d', to='new.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('bookingStatus', models.CharField(choices=[('BOOKED', 'BOOKED'), ('OPEN', 'OPEN')], default='OPEN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.TextField()),
                ('seatType', models.TextField()),
                ('seatClass', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateField()),
                ('gate', models.TextField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationNumber', models.TextField()),
                ('creationDate', models.DateField()),
                ('reservationStatus', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.flightschedule')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.seat'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileNo', models.TextField()),
                ('flightSeat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new.flightseat')),
            ],
        ),
    ]
