# Generated by Django 3.2.13 on 2022-04-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='seat',
        ),
        migrations.AddField(
            model_name='flightseat',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new.seat'),
            preserve_default=False,
        ),
    ]
