# Generated by Django 3.2.13 on 2022-04-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20220418_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='arrivalTime',
            field=models.DateField(default='2022-04-18'),
            preserve_default=False,
        ),
    ]
