# Generated by Django 3.2.13 on 2022-04-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20220418_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightreservation',
            old_name='flight',
            new_name='flightschedule',
        ),
    ]
