# Generated by Django 3.2.13 on 2022-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_rename_flight_flightreservation_flightschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='fare',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
