# Generated by Django 3.2.13 on 2022-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_flightschedule_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flightName',
            field=models.CharField(default='Nepal Airlines', max_length=20),
            preserve_default=False,
        ),
    ]
